backend:
  name: github
  repo: "1qk1/portfolio-test"

media_folder: static/assets
public_folder: assets

collections:
  - name: projects
    label: Project
    folder: "content"
    slug: "{{slug}}.md"
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: github, label: Github }
      - { name: url, label: URL }
