backend:
  name: github
  repo: "1qk1/portfolio-test"

media_folder: src/pages/projects/markdown/img
public_folder: /pages/projects/markdown/img

collections:
  - name: projects
    label: Projects
    folder: src/pages/projects/markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: github, label: Github }
      - { name: url, label: URL }
