backend:
  name: github
  repo: "1qk1/portfolio-test"

media_folder: src/images
public_folder: /images

collections:
  - name: projects
    label: Projects
    folder: "src/pages/projects/markdown/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: github, label: Github }
      - { name: url, label: URL }
