backend:
  name: github
  repo: "1qk1/skarlas.cc"

media_folder: static/assets
public_folder: assets

collections:
  - name: projects
    label: Project
    folder: "content"
    slug: "{{slug}}.md"
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {
          name: order,
          label: Order,
          widget: number,
          default: 0,
          valueType: int,
          min: 0,
        }
      - { name: description, label: Description }
      - { name: type, label: Type }
      - {
          name: technologies,
          label: Technologies Used,
          widget: list,
          default: [],
        }
      - { name: github, label: Github }
      - { name: url, label: URL }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field: { label: Image, name: image, widget: image }
      - { name: body, label: Body, widget: markdown }
